version: '3'

services:
  web:
    build: .
    command: /wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis


  db:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A mini_twitter_project worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  test:
    build: .
    command: pytest --cov=api --cov-report=term-missing --cov-report=html
    environment:
      - TESTING=True
    volumes:
      - .:/app
      - ./htmlcov:/app/htmlcov
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: