# Generated by Django 5.1.2 on 2024-10-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_followers_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
